name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Java
              uses: actions/setup-java@v1
              with:
                  java-version: '17'

            - name: Build with Maven
              run: ./mvnw clean package

            - name: Build Docker image
              run: docker build -t matthiasblank1990/calculationservice:${{ github.run_number }} .

            - name: Push Docker image
              run: |
                  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                  docker push matthiasblank1990/calculationservice:${{ github.run_number }}

            - name: Deploy to Azure
              run: az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myUniqueAppName12345 --deployment-container-image-name matthiasblank1990/calculationservice:${{ github.run_number }}
