openapi: 3.0.0
info:
  title: Calculate API
  version: 1.0.0
  description: API for performing calculations

paths:
  /calculate2:
    post:
      summary: Perform a calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateRequest'
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateResponse'
  /calculate:
    post:
      summary: Perform a calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateRequest'
      responses:
        '200':
          description: Successful calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateResponse'

  /calculateTax:
    post:
      summary: Perform a Tax-calculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateTaxRequest'
      responses:
        '200':
          description: Successful tax calculation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateTaxResponse'

components:
  schemas:
    CalculateRequest:
      type: object
      properties:
        number1:
          type: integer
        number2:
          type: integer
      required:
        - number1
        - number2
    CalculateTaxRequest:
      type: object
      properties:
        Steuerbilanzgewinn:
          type: number
      required:
        - Steuerbilanzgewinn
    CalculateResponse:
      type: object
      properties:
        result:
          type: integer
    CalculateTaxResponse:
      type: object
      properties:
        result:
          type: number
